[package]
name = "LastKingdom"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "launchers/wasm",
    "launchers/native",
]

[[bin]]
name="native-launcher"
path="launchers/native/src/main.rs"

# Optimizations for WASM
[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true

[dependencies]
bevy = "0.8.1"
image = "0.24.5"
winit = "0.26.1"
crossbeam-channel = "0.5"
bevy-inspector-egui = "0.13.0"
# bevy_egui="0.16.0"
# bevy_derive="0.8"
serde_json="1.0.88"
rand = "0.8.5"
rust-ini = "0.18.0"
bevy_rapier2d = {version = "0.18.0",features = ["debug-render"]}
sepax2d = "0.3.8"
broccoli = "6.0.2"

[profile.dev.package."*"]
opt-level = 1

[profile.dev]
opt-level = 1

