[package]
name = "lk2-client"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lk2-client"
path = "src/main.rs"

[[example]]
name = "audit_player"
path = "examples/audit_player.rs"

[[example]]
name = "simulate_forward"
path = "examples/simulate_forward.rs"

[[example]]
name = "debug_camera_view"
path = "examples/debug_camera_view.rs"

[features]
dev-dynamic-linking = ["bevy/dynamic_linking"]
audit-pretty-models = []

[dependencies]
bevy = { workspace = true }
bevy-inspector-egui = { workspace = true }
avian3d = { workspace = true }
bevy-tnua = { workspace = true }
bevy-tnua-avian3d = { workspace = true }
bevy_panorbit_camera = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
block-mesh = { workspace = true }
ndshape = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
lk2-core = { workspace = true, features = ["client-render"] }
lightyear = { workspace = true, features = ["leafwing", "client", "udp", "replication", "netcode"] }
lightyear_avian3d = { workspace = true }
lightyear_inputs_leafwing = { workspace = true }
lightyear_netcode = { version = "0.28" }
lightyear_connection = { version = "0.28", features = ["client"] }
leafwing-input-manager = { workspace = true }

[dev-dependencies]
